name: Build static production
on:
  workflow_dispatch:
    inputs:
      kuberta_system:

jobs:
  build:
    name: Build production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: docker://quay.csssr.cloud/csssr/kuberta-init-workflow:v1

      - name: Download CSSSR actions
        uses: actions/checkout@v4
        with:
          repository: CSSSR/actions
          ssh-key: ${{ secrets.DOWNLOAD_ACTIONS_SSH_KEY }}
          path: actions

      - uses: actions/checkout@v4
        with:
          path: make-sense

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: make-sense
        run: npm install --ci

      - name: Build production
        working-directory: make-sense
        run: npm run build

      - name: Import secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.csssr.com:8200
          jwtGithubAudience: ${{secrets.VAULT_JWT_AUDIENCE}}
          role: s3-ensi-app-cdn-upload
          method: jwt
          exportEnv: false
          secrets: |
            aws/sts/s3-cdn-upload access_key | AWS_ACCESS_KEY_ID ;
            aws/sts/s3-cdn-upload secret_key | AWS_SECRET_ACCESS_KEY ;
            aws/sts/s3-cdn-upload security_token | AWS_SESSION_TOKEN ;

      - uses: ./actions/upload-static/v1beta1
        with:
          project-id: ensi-make-sense
          files: ./make-sense/build
          auth: "aws:${{steps.secrets.outputs.AWS_ACCESS_KEY_ID}}:${{steps.secrets.outputs.AWS_SECRET_ACCESS_KEY}}:${{steps.secrets.outputs.AWS_SESSION_TOKEN}}"
