name: Production deploy
on:
  push:
    branches:
      - label-attributes
concurrency: production_environment

jobs:
  deploy:
    name: Build production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      deployments: write

    steps:
      - name: Download CSSSR actions
        uses: actions/checkout@v3
        with:
          repository: CSSSR/actions
          ssh-key: ${{ secrets.DOWNLOAD_ACTIONS_SSH_KEY }}
          path: actions

      - uses: actions/checkout@v3
        with:
          path: make-sense

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: make-sense
        run: npm install --ci

      - name: Build production
        working-directory: make-sense
        run: npm run build

      - name: Import secrets
        id: secrets
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: https://vault.csssr.com:8200
          jwtGithubAudience: ${{secrets.VAULT_JWT_AUDIENCE}}
          role: s3-ensi-app-cdn-upload
          method: jwt
          exportEnv: false
          secrets: |
            aws/sts/s3-cdn-upload access_key | AWS_ACCESS_KEY_ID ;
            aws/sts/s3-cdn-upload secret_key | AWS_SECRET_ACCESS_KEY ;
            aws/sts/s3-cdn-upload security_token | AWS_SESSION_TOKEN ;

      - name: Deploy to production
        uses: ./actions/deploy-static-site/v1beta1
        with:
          auth: 'aws:${{steps.secrets.outputs.AWS_ACCESS_KEY_ID}}:${{steps.secrets.outputs.AWS_SECRET_ACCESS_KEY}}:${{steps.secrets.outputs.AWS_SESSION_TOKEN}}'
          token: ${{ secrets.GITHUB_TOKEN }}
          site-type: spa
          project-id: ensi-make-sense
          files: ./make-sense/build
          no-previous-files: 'true'
          host: make-sense.csssr.com
          environment: production
          values: |
            cache: etag-only
            brotliCompression: enabled
